/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./components/AppFooter.vue')['default']
    BottomBar: typeof import('./components/common/BottomBar.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    InnerNavBar: typeof import('./components/common/InnerNavBar.vue')['default']
    LoginForm: typeof import('./components/auth/LoginForm.vue')['default']
    OuterFooter: typeof import('./components/common/OuterFooter.vue')['default']
    OuterNavbar: typeof import('./components/common/OuterNavbar.vue')['default']
    RegisterForm: typeof import('./components/auth/RegisterForm.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
